### ISSUE TITLE
Ficha Tecnica del producto

### ISSUE THREAD

**Issue by AndresFmunoz** [roadev/eco#80]
El orden de la ficha técnica seria: 

Residuo:
   - Papel:
   - Vidrio
   - Textiles 
   - Metales
   - Cartón: 
   - Plástico
   - Metales
   - Otro?: Cuál? _________________

Tipo de Residuo:

 - Papel:
          - Papeles (impresos o no)
          - Sobres comunes o de papel madera
          - Remitos, facturas, formularios, etc.
   - Vidrio:
          - Envases de alimentos
          - Bebidas
   - Textiles: 
          - Algodón
          - Lino 
   - Metales:
           - Latas y envases
           - Aluminios 
           - Metales ferrosos 
           - Chatarra
   - Cartón: tipos:
            - Cajas
            - Carpetas
            - Folletos
            - Guías telefónicas
            - Envases de cartón 
   - Plástico
            - Envases de comida y bebida
            - Vasos desechables
            - cubiertos desechables
            - Materas
            -  sillas
            - mesas,
   - Otro?: Cuál? _________________

  @roadev

**Comment by roadev** [comment]
Got it !

**Comment by roadev** [comment]
Doing it with: c11700c09bf397089d870c9118cb4ca746cdd42d

**Comment by roadev** [comment]
Done with: a01ff878f8c7346efd5f50a618951427bb5a9a4d
